---
sessions: []
jobs:
- id: 1
  name: Test Job
  pricing_type: fixed
  pricing_value: 1000.0
  client_id: 1
- id: 2
  name: Another Job
  pricing_type: fixed
  pricing_value: 1000.0
  client_id: 1
clients:
- id: 1
  name: Test Client
  address: SomeStreet 12
  city: New York
  postcode: 1234AA
invoices:
- id: 1
  date: 2017-02-03 16:39:39.000000000 +01:00
  client_id: 1
